version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /worker
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /recorder
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /cli
    schedule:
      interval: weekly
