"use client";

import { useState } from "react";
import { Copy, Download } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { SreMessageContent } from "@/components/sre/sre-message-content";

type SreIncidentBriefReportProps = {
  content: string;
  isStreaming?: boolean;
};

type SreIncidentBriefReportActionsProps = SreIncidentBriefReportProps & {
  incidentNumber: number;
  incidentTitle: string;
  disabled?: boolean;
};

function ensureReportFooter(content: string) {
  const trimmed = content.trim();
  if (/Generated by Supercheck AI/i.test(trimmed)) {
    return trimmed;
  }

  return `${trimmed}\n\n---\n**Generated by Supercheck AI.**`;
}

function normalizeReportMarkdown(input: string, appendFooter = true) {
  const content = appendFooter ? ensureReportFooter(input) : input.trim();
  if (/^#{1,3}\s/m.test(content)) {
    return content;
  }

  return `# Incident Investigation Report\n\n${content}`;
}

function safeFilePart(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 48);
}

export function SreIncidentBriefReport({
  content,
  isStreaming = false,
}: SreIncidentBriefReportProps) {
  const markdown = normalizeReportMarkdown(content, !isStreaming);
  const [showSource, setShowSource] = useState(false);

  return (
    <div className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-md border bg-muted/20">
      <div className="flex justify-end border-b p-2">
        <Button variant="ghost" size="sm" aria-pressed={showSource} onClick={() => setShowSource(!showSource)}>
          {showSource ? "Show preview" : "Show Markdown"}
        </Button>
      </div>
      <div role="region" aria-label="Evidence brief content" tabIndex={0} aria-busy={isStreaming} className="min-h-0 flex-1 overflow-auto break-words p-4 text-sm leading-6">
        {showSource ? <pre className="whitespace-pre-wrap break-words font-mono text-xs">{markdown}</pre> : <SreMessageContent content={markdown} />}
      </div>
    </div>
  );
}

export function SreIncidentBriefReportActions({
  incidentNumber,
  incidentTitle,
  content,
  disabled = false,
}: SreIncidentBriefReportActionsProps) {
  const markdown = normalizeReportMarkdown(content);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      toast.success("Brief copied to clipboard");
    } catch {
      toast.error("Failed to copy brief");
    }
  };

  const handleDownload = () => {
    try {
      const blob = new Blob([markdown], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `incident-${incidentNumber}-${safeFilePart(incidentTitle)}-brief.md`;
      document.body.append(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      toast.success("Brief downloaded");
    } catch {
      toast.error("Failed to download brief");
    }
  };

  return (
    <div className="flex shrink-0 items-center gap-2">
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={handleCopy}
        disabled={disabled}
      >
        <Copy className="h-3.5 w-3.5" />
        Copy
      </Button>
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={handleDownload}
        disabled={disabled}
      >
        <Download className="h-3.5 w-3.5" />
        Download
      </Button>
    </div>
  );
}
