"use client";

import { useEffect, useRef } from "react";
import Editor, { type Monaco, useMonaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";
import { useTheme } from "next-themes";
import { Copy, Download } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { getMonacoTheme, registerMonacoThemes } from "@/lib/monaco-config";

type SreIncidentBriefReportProps = {
  content: string;
};

type SreIncidentBriefReportActionsProps = SreIncidentBriefReportProps & {
  incidentNumber: number;
  incidentTitle: string;
};

function ensureReportFooter(content: string) {
  const trimmed = content.trim();
  if (/Generated by Supercheck AI/i.test(trimmed)) {
    return trimmed;
  }

  return `${trimmed}\n\n---\n**Generated by Supercheck AI.**`;
}

function normalizeReportMarkdown(input: string) {
  const content = ensureReportFooter(input);
  if (/^#{1,3}\s/m.test(content)) {
    return content;
  }

  return `# Incident Investigation Report\n\n${content}`;
}

function safeFilePart(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 48);
}

export function SreIncidentBriefReport({ content }: SreIncidentBriefReportProps) {
  const markdown = normalizeReportMarkdown(content);
  const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);
  const monaco = useMonaco();
  const { resolvedTheme } = useTheme();
  const editorTheme = getMonacoTheme(resolvedTheme);

  useEffect(() => {
    if (monaco && editorRef.current) {
      monaco.editor.setTheme(editorTheme);
    }
  }, [monaco, editorTheme]);

  const handleEditorMount = (
    editorInstance: editor.IStandaloneCodeEditor,
    monacoInstance: Monaco,
  ) => {
    editorRef.current = editorInstance;
    registerMonacoThemes(monacoInstance);
    monacoInstance.editor.setTheme(editorTheme);

    monacoInstance.languages.setLanguageConfiguration("markdown", {
      wordPattern:
        /(-?\d*\.\d\w*)|([^\`\~\!\@\#\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g,
    });
  };

  return (
    <div className="h-full min-h-0 min-w-0 overflow-hidden rounded-md border bg-muted/20">
      <Editor
        height="100%"
        language="markdown"
        theme={editorTheme}
        value={markdown}
        onMount={handleEditorMount}
        options={{
          readOnly: true,
          minimap: { enabled: false },
          wordWrap: "on",
          lineNumbers: "off",
          scrollBeyondLastLine: false,
          fontSize: 14,
          padding: { top: 16, bottom: 16 },
          folding: true,
          renderWhitespace: "none",
          automaticLayout: true,
          scrollbar: {
            vertical: "visible",
            horizontal: "hidden",
            verticalScrollbarSize: 8,
          },
        }}
      />
    </div>
  );
}

export function SreIncidentBriefReportActions({
  incidentNumber,
  incidentTitle,
  content,
}: SreIncidentBriefReportActionsProps) {
  const markdown = normalizeReportMarkdown(content);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      toast.success("Brief copied to clipboard");
    } catch {
      toast.error("Failed to copy brief");
    }
  };

  const handleDownload = () => {
    try {
      const blob = new Blob([markdown], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `incident-${incidentNumber}-${safeFilePart(incidentTitle)}-brief.md`;
      document.body.append(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      toast.success("Brief downloaded");
    } catch {
      toast.error("Failed to download brief");
    }
  };

  return (
    <div className="flex shrink-0 items-center gap-2">
      <Button type="button" variant="outline" size="sm" onClick={handleCopy}>
        <Copy className="h-3.5 w-3.5" />
        Copy
      </Button>
      <Button type="button" variant="outline" size="sm" onClick={handleDownload}>
        <Download className="h-3.5 w-3.5" />
        Download
      </Button>
    </div>
  );
}
