import { generateText, streamText } from "ai";
import { z } from "zod";

import {
  getActualModelName,
  getProviderModel,
  validateAIConfiguration,
} from "@/lib/ai/ai-provider";

export type BriefEvidenceInput = {
  id: string;
  title: string;
  summary: string | null;
  evidenceType: string;
  severity: string | null;
  confidence: string | null;
  sourceUri: string;
  rawContentExcerpt: string | null;
  observedAt: Date | null;
};

export type EvidenceBrief = {
  suspectedFailureDomain: string;
  summary: string;
  confidenceScore: number;
  citedEvidenceIds: string[];
  provider: "ai" | "fallback";
  modelId: string;
};

const briefSchema = z.object({
  suspectedFailureDomain: z.string().min(1).max(200),
  summary: z.string().min(1).max(5000),
  confidenceScore: z.number().min(0).max(1),
  citedEvidenceIds: z.array(z.string()).max(8),
});

export function fallbackBrief(
  evidence: BriefEvidenceInput[],
  modelId = "fallback",
): EvidenceBrief {
  const severe = evidence.find(
    (item) => item.severity === "sev1" || item.severity === "sev2",
  );
  const first = severe ?? evidence[0];

  if (!first) {
    return {
      suspectedFailureDomain: "Insufficient native evidence",
      summary: [
        "# Incident Investigation Report",
        "",
        "## Report Details",
        "- **Evidence Source**: Native Supercheck evidence",
        "- **Evidence Items**: 0",
        "",
        "## Executive Summary",
        "No native Supercheck evidence was available for this incident yet. Generate or link monitor, job, run, or connector evidence before relying on a root-cause summary.",
        "",
        "## What Changed",
        "- **Fact**: No stored native evidence was found for this incident.",
        "",
        "## Blast Radius",
        "- Unknown because no cited evidence establishes an affected scope.",
        "",
        "## Strongest Signals",
        "- None available.",
        "",
        "## Evidence Gaps",
        "- No cited records are available to validate a cause or affected scope.",
        "",
        "## Next Safe Checks",
        "- Link a relevant monitor, job, run, alert, or connector evidence source.",
        "- Regenerate the brief after native evidence is available.",
        "",
        "---",
        "**Generated by Supercheck AI.**",
      ].join("\n"),
      confidenceScore: 0.2,
      citedEvidenceIds: [],
      provider: "fallback",
      modelId,
    };
  }

  return {
    suspectedFailureDomain:
      first.evidenceType === "metric"
        ? "Monitoring signal"
        : "Execution artifact",
    summary: [
      "# Incident Investigation Report",
      "",
      "## Report Details",
      "- **Evidence Source**: Native Supercheck evidence",
      `- **Evidence Items**: ${evidence.length}`,
      `- **Primary Signal**: ${first.title}`,
      "",
      "## Executive Summary",
      "AI brief generation was unavailable, so this deterministic report summarizes the strongest native evidence without adding external assumptions.",
      "",
      "## What Changed",
      `- **Fact**: ${first.title}: ${first.summary ?? "No summary available."}`,
      "",
      "## Blast Radius",
      "- **Inference**: The affected scope is limited to the services and resources referenced by the cited evidence; broader impact is not established.",
      "",
      "## Strongest Signals",
      `- **Fact**: ${first.title} (${first.id}).`,
      "",
      "## Evidence",
      ...evidence
        .slice(0, 5)
        .map(
          (item) =>
            `- **${item.title}** (${item.evidenceType}): ${item.summary ?? "No summary available."}`,
        ),
      "",
      "## Evidence Gaps",
      "- Connector, topology, or change evidence may still be required to establish causality.",
      "",
      "## Next Safe Checks",
      "- Review the cited native evidence and affected service mapping.",
      "- Regenerate the brief when AI generation is available for richer analysis.",
      "",
      "---",
      "**Generated by Supercheck AI.**",
    ].join("\n"),
    confidenceScore: Number(first.confidence ?? 0.5),
    citedEvidenceIds: evidence.slice(0, 5).map((item) => item.id),
    provider: "fallback",
    modelId,
  };
}

function extractJson(text: string) {
  const trimmed = text.trim();
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  return fenced?.[1]?.trim() ?? trimmed;
}

function evidenceForPrompt(evidence: BriefEvidenceInput[]) {
  return evidence.slice(0, 20).map((item) => ({
    id: item.id,
    title: item.title,
    summary: item.summary,
    type: item.evidenceType,
    severity: item.severity,
    confidence: item.confidence,
    observedAt: item.observedAt?.toISOString() ?? null,
    sourceUri: item.sourceUri,
    excerpt: item.rawContentExcerpt,
  }));
}

function buildStructuredBriefPrompt(input: {
  incidentTitle: string;
  incidentSeverity: string;
  evidence: BriefEvidenceInput[];
}) {
  return `You are Supercheck's read-only AI SRE assistant.

Create a concise incident evidence brief using ONLY the cited native Supercheck evidence below. Do not invent external facts. If evidence is weak, say so.

Return JSON only with this exact shape:
{
  "suspectedFailureDomain": "short domain, e.g. monitor endpoint, job execution, k6 performance, unknown",
  "summary": "clean professional markdown report using the required format below",
  "confidenceScore": 0.0,
  "citedEvidenceIds": ["evidence id strings used for the claims"]
}

Required summary markdown format:
# Incident Investigation Report

## Report Details
- **Incident**: ${input.incidentTitle}
- **Severity**: ${input.incidentSeverity}
- **Evidence Source**: Native Supercheck evidence

## Executive Summary
[3-5 concise sentences with the overall verdict, strongest signals, and confidence level.]

## What Changed
[Facts only. State the observed change and cite evidence IDs.]

## Blast Radius
[State the affected services/resources. Label unsupported scope as unknown.]

## Strongest Signals
[Rank the most relevant evidence-backed signals. Label each claim Fact, Inference, or Hypothesis.]

## Evidence Reviewed
[Bullets summarizing the relevant native evidence records.]

## Likely Cause
[State the likely cause as an Inference or Hypothesis, or say it cannot be determined.]

## Evidence Gaps
[List missing evidence that prevents a higher-confidence conclusion.]

## Next Safe Checks
[Only bounded, read-only next checks justified by the evidence. Do not add generic monitoring advice.]

---
**Generated by Supercheck AI.**

Incident: ${input.incidentTitle}
Severity: ${input.incidentSeverity}
Evidence:
${JSON.stringify(evidenceForPrompt(input.evidence), null, 2)}`;
}

function buildStreamingBriefPrompt(input: {
  incidentTitle: string;
  incidentSeverity: string;
  evidence: BriefEvidenceInput[];
}) {
  return `You are Supercheck's read-only AI SRE assistant.

Write a concise Markdown incident evidence brief using ONLY the cited native Supercheck evidence below. Do not return JSON. Do not wrap the answer in a code fence. Do not invent external facts. If evidence is weak or contradictory, state that plainly.

Use exactly this Markdown structure:
# Incident Investigation Report

## Report Details
- **Incident**: ${input.incidentTitle}
- **Severity**: ${input.incidentSeverity}
- **Evidence Source**: Native Supercheck evidence
- **Evidence Items**: ${input.evidence.length}
- **Primary Signal**: [strongest evidence title, or "None available"]

## Executive Summary
[3-5 concise sentences with the overall verdict, strongest signals, and confidence level.]

## What Changed
[Facts only. State the observed change and include evidence IDs.]

## Blast Radius
[State the affected services/resources. Label unsupported scope as unknown.]

## Strongest Signals
[Rank evidence-backed signals. Label each claim Fact, Inference, or Hypothesis.]

## Evidence Reviewed
[Bullets summarizing the relevant native evidence records.]

## Likely Cause
[State the likely cause as an Inference or Hypothesis, or say it cannot be determined.]

## Evidence Gaps
[List missing evidence that prevents a higher-confidence conclusion.]

## Next Safe Checks
[Only bounded, read-only next checks justified by the evidence.]

---
**Generated by Supercheck AI.**

Incident: ${input.incidentTitle}
Severity: ${input.incidentSeverity}
Evidence:
${JSON.stringify(evidenceForPrompt(input.evidence), null, 2)}`;
}

function estimatedConfidence(evidence: BriefEvidenceInput[]) {
  const scores = evidence
    .map((item) => Number(item.confidence))
    .filter((value) => Number.isFinite(value));

  if (scores.length === 0) {
    return evidence.length > 0 ? 0.5 : 0.2;
  }

  return Math.max(
    0,
    Math.min(1, scores.reduce((sum, value) => sum + value, 0) / scores.length),
  );
}

export async function generateEvidenceBrief(input: {
  incidentTitle: string;
  incidentSeverity: string;
  evidence: BriefEvidenceInput[];
  userId: string;
  organizationId: string;
}): Promise<EvidenceBrief> {
  const modelId = getActualModelName();

  if (input.evidence.length === 0) {
    return fallbackBrief([], modelId);
  }

  try {
    validateAIConfiguration();

    const result = await generateText({
      model: getProviderModel(),
      prompt: buildStructuredBriefPrompt(input),
      temperature: 0.1,
      maxRetries: 2,
      maxOutputTokens: 1600,
      abortSignal: AbortSignal.timeout(45_000),
    });

    const parsed = briefSchema.safeParse(JSON.parse(extractJson(result.text)));
    if (!parsed.success) {
      return fallbackBrief(input.evidence, modelId);
    }

    const validIds = new Set(input.evidence.map((item) => item.id));
    return {
      ...parsed.data,
      citedEvidenceIds: parsed.data.citedEvidenceIds.filter((id) =>
        validIds.has(id),
      ),
      provider: "ai",
      modelId,
    };
  } catch (error) {
    console.warn(
      "[SRE Evidence Brief] Falling back to deterministic brief:",
      error,
    );
    return fallbackBrief(input.evidence, modelId);
  }
}

export async function streamEvidenceBrief(
  input: {
    incidentTitle: string;
    incidentSeverity: string;
    evidence: BriefEvidenceInput[];
    userId: string;
    organizationId: string;
  },
  onChunk: (chunk: string) => void | Promise<void>,
): Promise<EvidenceBrief> {
  const modelId = getActualModelName();

  const streamFallback = async (reason?: unknown) => {
    if (reason) {
      console.warn("[SRE Evidence Brief] Streaming fallback:", reason);
    }
    const fallback = fallbackBrief(input.evidence, modelId);
    await onChunk(fallback.summary);
    return fallback;
  };

  if (input.evidence.length === 0) {
    return streamFallback();
  }

  try {
    validateAIConfiguration();

    const result = await streamText({
      model: getProviderModel(),
      prompt: buildStreamingBriefPrompt(input),
      temperature: 0.1,
      maxRetries: 2,
      maxOutputTokens: 1800,
      abortSignal: AbortSignal.timeout(60_000),
    });

    const chunks: string[] = [];
    for await (const chunk of result.textStream) {
      chunks.push(chunk);
      await onChunk(chunk);
    }

    const summary = chunks.join("").trim();
    if (!summary) {
      return streamFallback(new Error("AI provider returned an empty brief"));
    }

    return {
      suspectedFailureDomain: "Native evidence analysis",
      summary,
      confidenceScore: estimatedConfidence(input.evidence),
      citedEvidenceIds: input.evidence.slice(0, 8).map((item) => item.id),
      provider: "ai",
      modelId,
    };
  } catch (error) {
    return streamFallback(error);
  }
}
