apiVersion: 1

datasources:
  - name: AISRE Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: AISRE Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: AISRE Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
